# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app-size"
client_id = "c0d41e836b9a166e82a27167bb9deb54"
application_url = "https://launched-we-basically-rapids.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://launched-we-basically-rapids.trycloudflare.com/auth/callback",
  "https://launched-we-basically-rapids.trycloudflare.com/auth/shopify/callback",
  "https://launched-we-basically-rapids.trycloudflare.com/api/auth/callback",
  "https://launched-we-basically-rapids.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "recommend-size.myshopify.com"
